### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by sebarys** [Philippus/julius#232]
Hi!

Are there any plans to publish this also for Scala 3?
Dependency to this lib is one of item that block us migrating one of application, it would be great to still use app instead of re-inventing the wheel :)

**Comment by Philippus** [comment]
Wow! Very curious how you are using this project, is it open source so I can see it?

**Comment by sebarys** [comment]
Unfortunately it is not. 

From usages I see we use only `RomanNumeralFromString` to parse roman numeral from string and convert it to `Int`.
Probably we can re-write it on our own as usage scope is pretty minimal but no code in codebase is the best code :)

**Comment by Philippus** [comment]
Resolved in https://github.com/Philippus/julius/pull/233.

**Comment by Philippus** [comment]
Version 1.2.0 supports Scala 3.
